name: play_with_dash_workspace

environment:
  sdk: ^3.9.0

# when needed update very good cli using
# dart pub global activate very_good_cli <version>

# when needed update melos using
# dart pub global activate melos <version>

dependencies:
  very_good_analysis: ^10.2.0

dev_dependencies:
  melos: ^6.3.3
