// Mocks generated by Mockito 5.4.4 from annotations
// in test_helper/test/src/stream_operations_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFuture_0<T1> extends _i1.SmartFake implements _i2.Future<T1> {
  _FakeFuture_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
        parent,
        parentInvocation,
      );
}

class _FakeStreamSubscription_1<T1> extends _i1.SmartFake
    implements _i2.StreamSubscription<T1> {
  _FakeStreamSubscription_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
        parent,
        parentInvocation,
      );
}

/// A class which mocks [Stream].
///
/// See the documentation for Mockito's code generation for more information.
class MockStream<T> extends _i1.Mock implements _i2.Stream<T> {
  MockStream() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isBroadcast =>
      (super.noSuchMethod(
            Invocation.getter(#isBroadcast),
            returnValue: false,
          )
          as bool);

  @override
  _i2.Future<int> get length =>
      (super.noSuchMethod(
            Invocation.getter(#length),
            returnValue: _i2.Future<int>.value(0),
          )
          as _i2.Future<int>);

  @override
  _i2.Future<bool> get isEmpty =>
      (super.noSuchMethod(
            Invocation.getter(#isEmpty),
            returnValue: _i2.Future<bool>.value(false),
          )
          as _i2.Future<bool>);

  @override
  _i2.Future<T> get first =>
      (super.noSuchMethod(
            Invocation.getter(#first),
            returnValue:
                _i3.ifNotNull(
                  _i3.dummyValueOrNull<T>(
                    this,
                    Invocation.getter(#first),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.getter(#first),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<T> get last =>
      (super.noSuchMethod(
            Invocation.getter(#last),
            returnValue:
                _i3.ifNotNull(
                  _i3.dummyValueOrNull<T>(
                    this,
                    Invocation.getter(#last),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.getter(#last),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<T> get single =>
      (super.noSuchMethod(
            Invocation.getter(#single),
            returnValue:
                _i3.ifNotNull(
                  _i3.dummyValueOrNull<T>(
                    this,
                    Invocation.getter(#single),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.getter(#single),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Stream<T> asBroadcastStream({
    void Function(_i2.StreamSubscription<T>)? onListen,
    void Function(_i2.StreamSubscription<T>)? onCancel,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #asBroadcastStream,
              [],
              {
                #onListen: onListen,
                #onCancel: onCancel,
              },
            ),
            returnValue: _i2.Stream<T>.empty(),
          )
          as _i2.Stream<T>);

  @override
  _i2.StreamSubscription<T> listen(
    void Function(T)? onData, {
    Function? onError,
    void Function()? onDone,
    bool? cancelOnError,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #listen,
              [onData],
              {
                #onError: onError,
                #onDone: onDone,
                #cancelOnError: cancelOnError,
              },
            ),
            returnValue: _FakeStreamSubscription_1<T>(
              this,
              Invocation.method(
                #listen,
                [onData],
                {
                  #onError: onError,
                  #onDone: onDone,
                  #cancelOnError: cancelOnError,
                },
              ),
            ),
          )
          as _i2.StreamSubscription<T>);

  @override
  _i2.Stream<T> where(bool Function(T)? test) =>
      (super.noSuchMethod(
            Invocation.method(
              #where,
              [test],
            ),
            returnValue: _i2.Stream<T>.empty(),
          )
          as _i2.Stream<T>);

  @override
  _i2.Stream<S> map<S>(S Function(T)? convert) =>
      (super.noSuchMethod(
            Invocation.method(
              #map,
              [convert],
            ),
            returnValue: _i2.Stream<S>.empty(),
          )
          as _i2.Stream<S>);

  @override
  _i2.Stream<E> asyncMap<E>(_i2.FutureOr<E> Function(T)? convert) =>
      (super.noSuchMethod(
            Invocation.method(
              #asyncMap,
              [convert],
            ),
            returnValue: _i2.Stream<E>.empty(),
          )
          as _i2.Stream<E>);

  @override
  _i2.Stream<E> asyncExpand<E>(_i2.Stream<E>? Function(T)? convert) =>
      (super.noSuchMethod(
            Invocation.method(
              #asyncExpand,
              [convert],
            ),
            returnValue: _i2.Stream<E>.empty(),
          )
          as _i2.Stream<E>);

  @override
  _i2.Stream<T> handleError(
    Function? onError, {
    bool Function(dynamic)? test,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #handleError,
              [onError],
              {#test: test},
            ),
            returnValue: _i2.Stream<T>.empty(),
          )
          as _i2.Stream<T>);

  @override
  _i2.Stream<S> expand<S>(Iterable<S> Function(T)? convert) =>
      (super.noSuchMethod(
            Invocation.method(
              #expand,
              [convert],
            ),
            returnValue: _i2.Stream<S>.empty(),
          )
          as _i2.Stream<S>);

  @override
  _i2.Future<dynamic> pipe(_i2.StreamConsumer<T>? streamConsumer) =>
      (super.noSuchMethod(
            Invocation.method(
              #pipe,
              [streamConsumer],
            ),
            returnValue: _i2.Future<dynamic>.value(),
          )
          as _i2.Future<dynamic>);

  @override
  _i2.Stream<S> transform<S>(_i2.StreamTransformer<T, S>? streamTransformer) =>
      (super.noSuchMethod(
            Invocation.method(
              #transform,
              [streamTransformer],
            ),
            returnValue: _i2.Stream<S>.empty(),
          )
          as _i2.Stream<S>);

  @override
  _i2.Future<T> reduce(
    T Function(
      T,
      T,
    )?
    combine,
  ) =>
      (super.noSuchMethod(
            Invocation.method(
              #reduce,
              [combine],
            ),
            returnValue:
                _i3.ifNotNull(
                  _i3.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #reduce,
                      [combine],
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #reduce,
                    [combine],
                  ),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<S> fold<S>(
    S? initialValue,
    S Function(
      S,
      T,
    )?
    combine,
  ) =>
      (super.noSuchMethod(
            Invocation.method(
              #fold,
              [
                initialValue,
                combine,
              ],
            ),
            returnValue:
                _i3.ifNotNull(
                  _i3.dummyValueOrNull<S>(
                    this,
                    Invocation.method(
                      #fold,
                      [
                        initialValue,
                        combine,
                      ],
                    ),
                  ),
                  (S v) => _i2.Future<S>.value(v),
                ) ??
                _FakeFuture_0<S>(
                  this,
                  Invocation.method(
                    #fold,
                    [
                      initialValue,
                      combine,
                    ],
                  ),
                ),
          )
          as _i2.Future<S>);

  @override
  _i2.Future<String> join([String? separator = r'']) =>
      (super.noSuchMethod(
            Invocation.method(
              #join,
              [separator],
            ),
            returnValue: _i2.Future<String>.value(
              _i3.dummyValue<String>(
                this,
                Invocation.method(
                  #join,
                  [separator],
                ),
              ),
            ),
          )
          as _i2.Future<String>);

  @override
  _i2.Future<bool> contains(Object? needle) =>
      (super.noSuchMethod(
            Invocation.method(
              #contains,
              [needle],
            ),
            returnValue: _i2.Future<bool>.value(false),
          )
          as _i2.Future<bool>);

  @override
  _i2.Future<void> forEach(void Function(T)? action) =>
      (super.noSuchMethod(
            Invocation.method(
              #forEach,
              [action],
            ),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<bool> every(bool Function(T)? test) =>
      (super.noSuchMethod(
            Invocation.method(
              #every,
              [test],
            ),
            returnValue: _i2.Future<bool>.value(false),
          )
          as _i2.Future<bool>);

  @override
  _i2.Future<bool> any(bool Function(T)? test) =>
      (super.noSuchMethod(
            Invocation.method(
              #any,
              [test],
            ),
            returnValue: _i2.Future<bool>.value(false),
          )
          as _i2.Future<bool>);

  @override
  _i2.Stream<R> cast<R>() =>
      (super.noSuchMethod(
            Invocation.method(
              #cast,
              [],
            ),
            returnValue: _i2.Stream<R>.empty(),
          )
          as _i2.Stream<R>);

  @override
  _i2.Future<List<T>> toList() =>
      (super.noSuchMethod(
            Invocation.method(
              #toList,
              [],
            ),
            returnValue: _i2.Future<List<T>>.value(<T>[]),
          )
          as _i2.Future<List<T>>);

  @override
  _i2.Future<Set<T>> toSet() =>
      (super.noSuchMethod(
            Invocation.method(
              #toSet,
              [],
            ),
            returnValue: _i2.Future<Set<T>>.value(<T>{}),
          )
          as _i2.Future<Set<T>>);

  @override
  _i2.Future<E> drain<E>([E? futureValue]) =>
      (super.noSuchMethod(
            Invocation.method(
              #drain,
              [futureValue],
            ),
            returnValue:
                _i3.ifNotNull(
                  _i3.dummyValueOrNull<E>(
                    this,
                    Invocation.method(
                      #drain,
                      [futureValue],
                    ),
                  ),
                  (E v) => _i2.Future<E>.value(v),
                ) ??
                _FakeFuture_0<E>(
                  this,
                  Invocation.method(
                    #drain,
                    [futureValue],
                  ),
                ),
          )
          as _i2.Future<E>);

  @override
  _i2.Stream<T> take(int? count) =>
      (super.noSuchMethod(
            Invocation.method(
              #take,
              [count],
            ),
            returnValue: _i2.Stream<T>.empty(),
          )
          as _i2.Stream<T>);

  @override
  _i2.Stream<T> takeWhile(bool Function(T)? test) =>
      (super.noSuchMethod(
            Invocation.method(
              #takeWhile,
              [test],
            ),
            returnValue: _i2.Stream<T>.empty(),
          )
          as _i2.Stream<T>);

  @override
  _i2.Stream<T> skip(int? count) =>
      (super.noSuchMethod(
            Invocation.method(
              #skip,
              [count],
            ),
            returnValue: _i2.Stream<T>.empty(),
          )
          as _i2.Stream<T>);

  @override
  _i2.Stream<T> skipWhile(bool Function(T)? test) =>
      (super.noSuchMethod(
            Invocation.method(
              #skipWhile,
              [test],
            ),
            returnValue: _i2.Stream<T>.empty(),
          )
          as _i2.Stream<T>);

  @override
  _i2.Stream<T> distinct([
    bool Function(
      T,
      T,
    )?
    equals,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(
              #distinct,
              [equals],
            ),
            returnValue: _i2.Stream<T>.empty(),
          )
          as _i2.Stream<T>);

  @override
  _i2.Future<T> firstWhere(
    bool Function(T)? test, {
    T Function()? orElse,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #firstWhere,
              [test],
              {#orElse: orElse},
            ),
            returnValue:
                _i3.ifNotNull(
                  _i3.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #firstWhere,
                      [test],
                      {#orElse: orElse},
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #firstWhere,
                    [test],
                    {#orElse: orElse},
                  ),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<T> lastWhere(
    bool Function(T)? test, {
    T Function()? orElse,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #lastWhere,
              [test],
              {#orElse: orElse},
            ),
            returnValue:
                _i3.ifNotNull(
                  _i3.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #lastWhere,
                      [test],
                      {#orElse: orElse},
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #lastWhere,
                    [test],
                    {#orElse: orElse},
                  ),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<T> singleWhere(
    bool Function(T)? test, {
    T Function()? orElse,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #singleWhere,
              [test],
              {#orElse: orElse},
            ),
            returnValue:
                _i3.ifNotNull(
                  _i3.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #singleWhere,
                      [test],
                      {#orElse: orElse},
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #singleWhere,
                    [test],
                    {#orElse: orElse},
                  ),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<T> elementAt(int? index) =>
      (super.noSuchMethod(
            Invocation.method(
              #elementAt,
              [index],
            ),
            returnValue:
                _i3.ifNotNull(
                  _i3.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #elementAt,
                      [index],
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #elementAt,
                    [index],
                  ),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Stream<T> timeout(
    Duration? timeLimit, {
    void Function(_i2.EventSink<T>)? onTimeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #timeout,
              [timeLimit],
              {#onTimeout: onTimeout},
            ),
            returnValue: _i2.Stream<T>.empty(),
          )
          as _i2.Stream<T>);
}
