name: simplebingo

concurrency:
  group: $-$
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      coverage_excludes: "*.g.dart *.freezed.dart" # defaults to "" (none)
      working_directory: apps/simplebingo # defaults to "." (the top-level directory)

  spell-check:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/spell_check.yml@v1
    with:
      continue-on-error: true
      includes: |
        **/*.md
      modified_files_only: false
